config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session GET    /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        users#show
#                           create_vote GET    /create_vote(.:format)                                                                   votes#create
#                                  vote GET    /vote(.:format)                                                                          votes#show
#                                groups GET    /groups(.:format)                                                                        groups#index
#                               demands GET    /demands(.:format)                                                                       votes#index
#                              my_votes GET    /my_votes(.:format)                                                                      my_votes#index
#                         group_profile GET    /group_profile(.:format)                                                                 groups#show
#                       demands_profile GET    /demands_profile(.:format)                                                               votes#index
#                                demand GET    /demand(.:format)                                                                        votes#show
#                         demand_update GET    /demand_update(.:format)                                                                 votes#update
#                             new_group POST   /new_group(.:format)                                                                     groups#create
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#show'

  get '/vote',   to: 'votes#show'
  get '/groups', to: 'groups#index'
  get '/demands', to: 'votes#index'
  get '/my_votes', to: 'my_votes#index'
  get '/group_profile', to: 'groups#show'
  get '/demands_profile', to: 'votes#index'
  get '/demand',   to: 'votes#show'
  get '/demand_update',   to: 'votes#update'
  get '/groups_new', to: 'groups#new'
  post '/groups_new',   to: 'groups#create'
  get '/demands_new',   to: 'votes#new'
  post '/demands_new', to: 'votes#create'
  get '/group_stats', to: 'my_votes#show_group'
  get '/vote_stats', to: 'my_votes#show'
  get '/group_stats_freq', to: 'my_votes#show_group_freq'
end

app/models/my_vote.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: my_votes
#
#  id         :bigint           not null, primary key
#  votes_id   :integer
#  counter    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#

class MyVote < ApplicationRecord
  belongs_to :user
end

app/controllers/my_votes_controller.rb
# frozen_string_literal: true

class MyVotesController < ApplicationController
  before_action :authenticate_user!
  def create
    @my_vote = current_user.my_votes.new(post_params)

    if @my_vote.save

      render :index, alert: 'Your Vote was successfully created.'
    else

      render :index, alert: 'Vote was not created.'
    end
  end

  def show
    @data = helpers.get_data(params[:votes_id])
    @data
  end

  def show_group
    @group = Group.find_by_id(params[:group_id])
  end

  def show_group_freq
    return unless params[:group_id]

    @group = Group.find_by_id(params[:group_id])
    @bar_data = [%w[Demand Votes]]
    organizer = {}

    @group.votes.each do |vote|
      organizer[vote.name] = vote.counter
    end
    organizer = organizer.sort_by { |_k, v| v }

    organizer.each do |name, votes|
      @bar_data << [name[0..15] + '...', votes]
    rescue StandardError
      @bar_data << [name, votes]
    end
    @bar_data
  end

  def index; end
end

app/helpers/my_votes_helper.rb
# frozen_string_literal: true

module MyVotesHelper
  def get_data(vote)
    votes = MyVote.where(votes_id: vote)
    data = {}
    collaborators = {}
    coll_ids = []

    votes.each do |vot|
      collaborators[vot.user_id] = []
    end

    collaborators.each do |key, _value|
      coll_ids.push(User.find_by_id(key).name)
      my_votes = votes.where(user_id: key)
      my_votes = my_votes.order(:created_at)
      my_votes.each do |vot|
        collaborators[key] << vot.counter
      end
    end

    max_len = []
    collaborators.each do |key, _value|
      max_len << collaborators[key].length
    end

    max_len = max_len.max

    collaborators.each do |key, _value|
      next unless collaborators[key].length < max_len

      (max_len - collaborators[key].length).times do
        collaborators[key] << collaborators[key].last
      end
    end

    cum_data = []
    (1..max_len - 1).each do |index|
      row = []
      row << index
      input = []
      collaborators.each do |key, _value|
        input.push(collaborators[key][index])
      end
      input.each do |datum|
        row.push(datum)
      end
      cum_data.push(row)
    end

    data[:data] = cum_data
    data[:coll_ids] = coll_ids
    data[:title] = Vote.find_by_id(vote).name
    data[:votes_id] = vote
    data
  end
end

app/views/my_votes/index.html.erb
 
<div class="back_my_votes_group">

    <div class="container d-flex justify-content-between">

        <div class="d-flex justify-content-center align-content-center">
            
            <div class=" text-center">
                <img src=<%= current_user.gravatar %> alt="User avatar" class = 'my_votes_avatar rounded-circle img-fluid'>
            </div>
                    
        </div>
            
        <div class="d-flex justify-content-center align-content-center main_my_vote">
            <div class="text-center d-flex justify-content-center ">
                <span id = 'my_votes_name'> <%=current_user.name %></span>
            </div>
        </div>
    </div>


    <div class="d-flex justify-content-center align-content-center">
        <div class="groups_label text-center d-flex justify-content-center align-content-center">
        <img src="https://i.imgur.com/4NfuoA0.png" alt="">
        </div>
    </div>

    <div id="demo" class="carousel slide groups_carousel" data-ride="carousel">
        
        <div class="carousel-inner">
            
            <div class="carousel-item active avatar_carousel d-flex justify-content-center align-items-center">
                <img src= <%= current_user.gravatar%> alt="group" class = " d-none img-fluid img-thumbnail rounded-circle avatar_group_my_votes">
            </div>
            
            <% current_user.groups.each do |group| %>
                            
                <div class="carousel-item carousel_square" >
                    <a href= <%= group_stats_path(group_id: group.id)%> >
                        <div class = "d-flex justify-content-center align-items-center">
                            <div class="text-white ">
                                <img src= <%=group.imagen_url%> alt="group" class = "img-fluid img-thumbnail rounded-circle group_foto_my_votes">
                                
                            </div>
                        </div>
                    </a>
                </div>
                
            <% end %>
            
        </div>

            
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>

    </div>

    <div class="d-flex justify-content-center align-content-center">
        <div class=" groups_label text-center d-flex justify-content-center align-content-center">
            <img src="https://i.imgur.com/TQVn49Z.png" alt="">
        </div>
    </div>

    <div class='d-flex justify-content-center'>

        <div>
            
            <div class="my_votes_demand_list_index ">
                <div class="demands_list_my_votes_group ">
                    <ul class="list-group">
                        <% current_user.votes.each do |demand| %>
                            <a href=<%= vote_url(votes_id: demand.id) %>>
                                <li class="list-group-item d-flex justify-content-between align-items-center demand_my_votes_item mb-1">
                                    <%=demand.name%>
                                    <span class="badge badge-success badge-pill counter_for_demand_list">
                                        <%=demand.counter%>
                                    </span>
                                </li>
                            </a>
                            
                        <%end%>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</div>

<div class="foot_icons d-flex justify-content-center mt-5 pt-5">
        
    <div class='d-flex justify-content-center'>
            <a href=<%= root_url %> class = 'home_button'>
                <img src="https://i.imgur.com/JcpkRZh.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
    </div>
    <div class='d-flex justify-content-center '>
        <a href=<%=  groups_url %> class = 'groups_home_button'>
            <img src="https://i.imgur.com/xbEKtIa.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
    
    <div class='d-flex justify-content-center '>
        <a href=<%=  demands_profile_url %> class = 'demands_list_link'>
            <img src="https://i.imgur.com/MRW2EsQ.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
</div>

app/views/my_votes/show.html.erb
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
      google.charts.load('current', {'packages':['line']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = new google.visualization.DataTable();
      var coll_ids = <%== @data[:coll_ids] %>
      data.addColumn('number', 'Day');
      console.log(coll_ids)
      for (let step = 0; step < coll_ids.length; step++) {
            data.addColumn('number', coll_ids[step]);
        
          }
      data.addRows(<%=raw(@data[:data])%>);

      var options = {
        chart: {
          title: '<%= raw(@data[:title]) %>',
          
        },
        width: 900,
        height: 500,
        axes: {
          x: {
            0: {side: 'top'}
          }
        }
      };

      var chart = new google.charts.Line(document.getElementById('line_top_x'));

      chart.draw(data, google.charts.Line.convertOptions(options));
    }
  </script>

app/views/my_votes/show_group.html.erb
<div class="group_stats_gral">
    <img class="card-img-top_show_group img-fluid" src=<%= @group.imagen_url%> alt="Group image">
    <div class="d-flex justify-content-center ">
        
        <div class="card group_my_votes">
            
            <div class="card-body info_group_my_votes">
                <h5 class="card-title title_group text-center"><%=@group.name%></h5>
                <p class="card-text my_group_description" > <%=@group.description%> </p>
            </div>
        </div>
    </div>
</div>
        
<section class = 'my_votes_data' >
    
    <div class="group_totals">
        <h4 class= 'total_groups text-center'>
            <span class='total_votes_title_group'>
                TOTAL VOTES: 
            </span>
            <span class='total_votes_group'>
                <%= @group.group_total%>
            </span>
        </h4>
    </div>

    <div class="d-flex justify-content-center  align-content-center my_votes_data_1">
        <div class="d-flex flex-column">

            <div  class="collab_title_1 ">
                Collaborators
            </div>
            <div class="users_counter d-flex justify-content-between">
                
                <span>
                    demand creator
                </span>
                <span>
                    Votes
                </span>
                
            </div>

            <div class="collaborators ">
                        
                <% @group.my_collaborators(current_user.id).each do |col_id, collaborator|%>
                    <div class= 'collaborator_names text-center d-flex justify-content-between'>
                        
                        <div class="modal fade modal_show_group" id=<%= 'myModal'+col_id.to_s%>>
                            <div class="modal-dialog">
                                
                                <div class="modal-content_show_group">
                                    
                                    <div class="modal-header_show_group d-flex justify-content-around align-content-center">
                                        <span id = 'thisdemands'>
                                            Created by: <%= ' '+ User.find_by_id(col_id).name %>
                                        </span>
                                    </div>

                                    <div class="modal-body_show_group d-flex flex-column justify-content-center">
                                        
                                        <% collaborator.keys.each do |vote| %>
                                            
                                            <% if vote != :total_counter %>
                                                <a href=<%= vote_url(votes_id:vote) %> class='bad_link'>
                                                    <div class="card_my_vote_show_group d-flex justify-items-center" >
                                                        
                                                        <img class="img-fluid image_modal_votes_show_group rounded-circle" style="width:10rem;height:10rem" src=<%= Vote.find_by_id(vote).gravatar_url %> alt="Card image cap">
                                                        
                                                        
                                                            <div class="vote_my_votes_body">
                                                                
                                                                <span id = 'user_name_card_my_votes'>
                                                                    <%= collaborator[vote][:name]%>
                                                                </span>
                                                                                                                            
                                                                <div class = 'counter_scroll_demands_my_vote_parent'>
                                                                    <span class = 'counter_scroll_demands_my_vote'>
                                                                        <%= collaborator[vote][:counter]%>
                                                                    </span>
                                                                </div>

                                                            </div>
                                                    </div>
                                                </a>
                                            <%end%>

                                        <% end %>
                                        
                                    </div>

                                    <div class=" foot_1 d-flex justify-content-center">
                                        <img  data-dismiss="modal" type="button" class = 'img-fluid rounded-circle pp' src= <%= User.find_by_id(col_id).gravatar %> alt="">                                     
                                    </div>

                                </div>
                                
                            </div>
                        </div>

                        <a class='collabs' data-toggle="modal" data-target=<%= '#myModal'+col_id.to_s%>>
                            <%= User.find_by_id(col_id).name %>  
                        </a>
                        
                        <span class='collabs'>
                            <%= collaborator[:total_counter] %>
                        </span>

                    </div>
                <% end %>

            </div>

        </div>
    </div>
    
    <div class='d-flex justify-content-center my_votes_demands_list'>
        <div>
            <div class="collab_title">
                
            Demands of the Group
                    
            </div>
            
            <div class="my_votes_demand_list ">
                <div class="demands_list_my_votes ">
                    <ul class="list-group ">
                        <% @group.votes.each do |demand| %>
                            <a href=<%= vote_url(votes_id:demand.id) %>>
                                <li class="list-group-item d-flex justify-content-between align-items-center demand_my_votes_item">
                                    <%=demand.name%>
                                    <span class="badge badge-success badge-pill counter_for_demand_list">
                                        <%=demand.counter%>
                                    </span>
                                </li>
                            </a>
                            
                        <%end%>

                    </ul>
                </div>
            </div>

        </div>
    </div>
        
    <div class="foot_icons d-flex justify-content-center mt-5 pt-5">

        <div class='d-flex justify-content-center'>
                <a href=<%= root_url %> class = 'home_button'>
                    <img src="https://i.imgur.com/JcpkRZh.png" alt="" class='img-fluid imagen_vote_show'>
                </a>
        </div>
        <div class='d-flex justify-content-center '>
            <a href=<%=  groups_url %> class = 'groups_home_button'>
                <img src="https://i.imgur.com/xbEKtIa.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
        <div class='d-flex justify-content-center'>
            <a href=<%= group_stats_freq_url(group_id: @group.id) %> class='demand_stats_button' >
                <img src="https://i.imgur.com/XQ0rn90.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
        <div class='d-flex justify-content-center '>
            <a href=<%=  demands_profile_url %> class = 'demands_list_link'>
                <img src="https://i.imgur.com/MRW2EsQ.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
    </div>
        
</section>

app/views/my_votes/show_group_freq.html.erb
<div class="container d-flex justify-content-center align-content-center ">
    <div id="freq_group" style="">
    </div>
    <a href=<%= my_votes_url %> class = 'back_button_index_groups' id='back_group_stats_show'>
        <img src="https://i.imgur.com/BEcgpsg.png" alt="" class='img-fluid imagen_vote_show'>
    </a>
</div>