config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session GET    /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        users#show
#                           create_vote GET    /create_vote(.:format)                                                                   votes#create
#                                  vote GET    /vote(.:format)                                                                          votes#show
#                                groups GET    /groups(.:format)                                                                        groups#index
#                               demands GET    /demands(.:format)                                                                       votes#index
#                              my_votes GET    /my_votes(.:format)                                                                      my_votes#index
#                         group_profile GET    /group_profile(.:format)                                                                 groups#show
#                       demands_profile GET    /demands_profile(.:format)                                                               votes#index
#                                demand GET    /demand(.:format)                                                                        votes#show
#                         demand_update GET    /demand_update(.:format)                                                                 votes#update
#                             new_group POST   /new_group(.:format)                                                                     groups#create
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#show'

  get '/vote',   to: 'votes#show'
  get '/groups', to: 'groups#index'
  get '/demands', to: 'votes#index'
  get '/my_votes', to: 'my_votes#index'
  get '/group_profile', to: 'groups#show'
  get '/demands_profile', to: 'votes#index'
  get '/demand',   to: 'votes#show'
  get '/demand_update',   to: 'votes#update'
  get '/groups_new', to: 'groups#new'
  post '/groups_new',   to: 'groups#create'
  get '/demands_new',   to: 'votes#new'
  post '/demands_new', to: 'votes#create'
  get '/group_stats', to: 'my_votes#show_group'
  get '/vote_stats', to: 'my_votes#show'
  get '/group_stats_freq', to: 'my_votes#show_group_freq'
end

app/models/group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#  description :string
#  imagen_url  :string
#
require 'set'
class Group < ApplicationRecord
  belongs_to :user
  has_many :votes
  validates :name, presence: true, length: { maximum: 20 }

  def group_total
    total = 0
    demands = votes
    demands.each do |demand|
      total += demand.counter
    end
    total
  end

  def my_collaborators(current_user)
    collaborators = {}
    votes.where.not(user_id: current_user).each do |vote|
      collaborators[vote.user_id] = { total_counter: 0 } if collaborators[vote.user_id].nil?

      collaborators[vote.user_id][vote.id] = { name: vote.name,
                                               description: vote.description,
                                               counter: vote.counter,
                                               avatar: vote.gravatar_url }
      collaborators[vote.user_id][:total_counter] += vote.counter
    end

    collaborators
  end

  def cumulative; end

  def all_collaborators
    @demands = votes
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find_by_id(params[:group_id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Post was successfully created.'

    else

      render :index, alert: 'Post was not created.'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :imagen_url)
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/index.html.erb
<div class="group_show_back">
    
    <a  href= <%= groups_new_url%> >
        <img src="https://i.imgur.com/yFmVzKG.png" alt="uptitle" class='new_button'>
    </a>
    
    <div class="d-flex justify-content-center align-content-center">
        <div class=" groups_label_index_g text-center mb-5">
           
                <img src="https://i.imgur.com/mrFgPxb.png" alt="downtitle" class='down_title_groups  img-responsive'>
            
        </div>
    </div>

    <div id= 'content_grl'>
        <a href=<%= root_url %> class = 'home_button_groups'>
            <img src="https://bit.ly/39poQlf" alt="" class='img-responsive imagen_vote_show'>
        </a>
        
    </div>

    <div class='d-flex justify-content-center groups_scroll_show'>
        
        <ul class="ul_scroll_groups_index ">
            <% @groups.each do |group| %>
                <% if group.user_id != current_user.id%>
                
                    <a class = 'gral_link_for_group'href=<%= group_profile_url(group_id: group.id) %>>

                        <div class="card pb-5 unit_group">
                            <div class='photo_top_group_card'>
                                <img class="card-img-top " src=<%=group.imagen_url%>>
                                
                            </div>
            
                            
                            <div class="card-block text-center center_card_groups_index">
                                <div class="profile">
                                    <img class= 'rounded-circle img-fluid author_image' src=<%=User.find_by_id(group.user_id).gravatar%> alt="">
                                </div>
                                <h4 class="card-title mt-3 group_title_scroll"><%=group.name%></h4>
                                <div class="meta meta_card_relative">
                                    <h6 class='meta_card_group_index'><%=group.description%></h6>
                                    
                                </div>
                                <div class="card-text card-text_groups">
                                    Created by: <%=User.find_by_id(group.user_id).name%>
                                    <%begin%>
                                        <p>Last updated <%= group.votes.last.created_at %></p>
                                    <%rescue%>
                                        <p>No demands for this group</p>
                                    <%end%>
                                </div>
                                    
                            </div>
                        </div>
                    </a>                   
                <%end%>
            <%end%>

        </ul>
    </div>
    <footer class="footer">
      <div class="container">
        <img src="https://i.imgur.com/Apw10z1.png" alt="downtitle" class='down_title_groups_demo  img-responsive'>
      </div>
    </footer>
    
    
</div>

app/views/groups/new.html.erb
<div class='container login_form d-flex justify-content-center'>
  <img src="https://i.imgur.com/JekPvMp.png" alt="Login" class = "img-fluid login_form">
</div>

<div class="container d-flex justify-content-center create_group sign_form">
    <%= form_for(@group, url: '/groups_new') do |f| %>
        <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true%>
        </div>
        <div class="field">
            <%= f.label :description %><br />
            <%= f.text_field :description, autofocus: true%>
        </div>
        <div class="field">
            <%= f.label :image_url %><br />
            <%= f.text_field :imagen_url, autofocus: true%>
        </div>
        <%= f.submit 'create', class: 'btn btn-secondary' %>
    <% end %>
</div>

app/views/groups/show.html.erb
<div class="group_show_back_profile">

</div>


<div class="group_stats_gral">
    <img class="card-img-top_show_group img-fluid" src=<%= @group.imagen_url%> alt="Group image">
    <div class="d-flex justify-content-center ">
        
        <div class="card group_my_votes justify-content-center">
            
            <div class="card-body info_group_my_votes">
                <h5 class="card-title title_group text-center"><%=@group.name%></h5>
                <p class="card-text my_group_description" > <%=@group.description%> </p>
            </div>
        </div>
    </div>
</div>

<div class='d-flex justify-content-center'>

        <div>
            <div class="my_votes_demand_list_index_group ">
                <div class="demands_list_my_votes_group ">
                    <ul class="list-group">
                        <% @group.votes.each do |demand| %>
                            <a href=<%= vote_url(votes_id: demand.id) %>>
                                <li class="list-group-item d-flex justify-content-between align-items-center demand_my_votes_item mb-1">
                                    <%=demand.name%>
                                    <span class="badge badge-success badge-pill counter_for_demand_list">
                                        <%=demand.counter%>
                                    </span>
                                </li>
                            </a>
                            
                        <%end%>
                    </ul>
                </div>
            </div>
        </div>
</div>

<div class="foot_icons d-flex justify-content-center mt-5 pt-5 for_group_show">

    <div class='d-flex justify-content-center'>
            <a href=<%= root_url %> class = 'home_button'>
                <img src="https://i.imgur.com/JcpkRZh.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
    </div>
    <div class='d-flex justify-content-center '>
        <a href=<%=  groups_url %> class = 'groups_home_button'>
            <img src="https://i.imgur.com/xbEKtIa.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
    <div class='d-flex justify-content-center'>
        <a href=<%= group_stats_freq_url(group_id: @group.id) %> class='demand_stats_button' >
            <img src="https://i.imgur.com/XQ0rn90.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
    <div class='d-flex justify-content-center '>
        <a href=<%=  demands_profile_url %> class = 'demands_list_link'>
            <img src="https://i.imgur.com/MRW2EsQ.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
    <div class='d-flex justify-content-center '>
        <a href=<%=  demands_new_url(group_id: @group.id) %> class = 'demands_list_link'>
            <img src="https://i.imgur.com/Nxx48DE.png" alt="" class='img-fluid imagen_vote_show'>
        </a>
    </div>
    
</div>