config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session GET    /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        users#show
#                           create_vote GET    /create_vote(.:format)                                                                   votes#create
#                                  vote GET    /vote(.:format)                                                                          votes#show
#                                groups GET    /groups(.:format)                                                                        groups#index
#                               demands GET    /demands(.:format)                                                                       votes#index
#                              my_votes GET    /my_votes(.:format)                                                                      my_votes#index
#                         group_profile GET    /group_profile(.:format)                                                                 groups#show
#                       demands_profile GET    /demands_profile(.:format)                                                               votes#index
#                                demand GET    /demand(.:format)                                                                        votes#show
#                         demand_update GET    /demand_update(.:format)                                                                 votes#update
#                             new_group POST   /new_group(.:format)                                                                     groups#create
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#show'

  get '/vote',   to: 'votes#show'
  get '/groups', to: 'groups#index'
  get '/demands', to: 'votes#index'
  get '/my_votes', to: 'my_votes#index'
  get '/group_profile', to: 'groups#show'
  get '/demands_profile', to: 'votes#index'
  get '/demand',   to: 'votes#show'
  get '/demand_update',   to: 'votes#update'
  get '/groups_new', to: 'groups#new'
  post '/groups_new',   to: 'groups#create'
  get '/demands_new',   to: 'votes#new'
  post '/demands_new', to: 'votes#create'
  get '/group_stats', to: 'my_votes#show_group'
  get '/vote_stats', to: 'my_votes#show'
  get '/group_stats_freq', to: 'my_votes#show_group_freq'
end

app/models/vote.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: votes
#
#  id           :bigint           not null, primary key
#  name         :string
#  description  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  gravatar_url :string
#  counter      :integer
#  group_id     :bigint
#  user_id      :bigint
#

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :name, presence: true
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  def new
    @vote = Vote.new
    @group_id = params[:group_id]
  end

  def create
    @vote = current_user.votes.new(vote_params)

    if @vote.save

      redirect_to demand_url(votes_id: @vote.id), notice: 'Demand was successfully created.'
    else

      render :show, alert: 'demand was not created.'
    end
  end

  def show
    @vote = Vote.find(params[:votes_id])
  end

  def index
    @demands = Vote.all
  end

  # rubocop:disable Metrics/AbcSize
  def update
    votes = Vote.find_by_id(params[:votes_id])

    case params[:vote]
    when 'up'
      votes.counter += 1
      votes.save
      begin
        count = current_user.my_votes.where(votes_id: votes.id).last.counter
        current_user.my_votes.new(votes_id: votes.id, counter: count + 1).save
      rescue 
        current_user.my_votes.new(votes_id: votes.id, counter: 1).save
      end

    when 'down'
      votes.counter -= 1
      votes.save
      begin
        count = current_user.my_votes.where(votes_id: votes.id).last.counter
        current_user.my_votes.new(votes_id: votes.id, counter: count - 1).save
      rescue 
        current_user.my_votes.new(votes_id: votes.id, counter: 1).save
      end
    end
    redirect_to vote_url(votes_id: votes.id)
  end
  # rubocop:enable Metrics/AbcSize

  private

  def vote_params
    params.require(:vote).permit(:name, :description, :gravatar_url, :group_id, :counter)
  end
end

app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

app/views/votes/index.html.erb
<div class="group_show_back">
    
    <div class="group_list_votes_index">

        <a class="new_link_modal text-center d-flex justify-content-between" href= <%=groups_url%> type="button" data-toggle="modal" data-target="#modal_new_demand">
            <img src="https://i.imgur.com/yFmVzKG.png" alt="uptitle" class='new_link_votes'>
        </a>
        <div class="modal fade" id="modal_new_demand">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content modal_new_demand">
                
                    <!-- Modal Header -->
                    <div class="modal-header header_new_demand">
                        <h4 class="modal-title title_new_demand">PICK A GROUP</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body body_demands_new_list">
                            <%Group.all.each do |group|%>
                                <a class="groups_list_item_new_demand d-flex justify-content-start align-content-center" href=<%=demands_new_url(group_id: group.id)%>>
                                    <img src=<%=group.imagen_url%> class='img-fluid rounded-circle' style='width:80px;height:80px;margin-right:5rem;'>
                                    <span><%=group.name%></span>
                                </a>
                            <%end%>

                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id='button_submit_new_demand'>Close</button>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
        
    <div class="d-flex justify-content-center align-content-center">
        <div class=" groups_label_index_votes text-center mb-5">
           
                <img src="https://i.imgur.com/CgFTaF0.png" alt="downtitle" class='  img-responsive' style='width:40rem;'>
            
        </div>
    </div>

    <div id= 'content_grl'>
        <a href=<%= root_url %> class = 'home_button_votes'>
            <img src="https://bit.ly/39poQlf" alt="" class='img-responsive imagen_vote_show_votes'>
        </a>
        
    </div>

    <div class='d-flex justify-content-center groups_scroll_show'>
        
        <ul class="ul_scroll_groups_index ">
            <% @demands.each do |demand| %>
                
                
                    <a class = 'gral_link_for_group'href=<%= vote_url(votes_id: demand.id) %>>

                        <div class="card pb-5 unit_group">
                            <div class='photo_top_group_card'>
                                <img class="card-img-top " src=<%=demand.gravatar_url%>>
                                
                            </div>
            
                            
                            <div class="card-block text-center center_card_groups_index">
                                <div class="profile">
                                    <img class= 'rounded-circle img-fluid author_image' src=<%=User.find_by_id(demand.user_id).gravatar%> alt="">
                                </div>
                                <h4 class="card-title mt-3 group_title_scroll"><%=demand.name%></h4>
                                <div class="meta meta_card_relative">
                                    <h6 class='meta_card_votes_index'><%=demand.description%></h6>
                                    
                                </div>
                                <div class="card-text card-text_groups">
                                    Created by: <%=User.find_by_id(demand.user_id).name%>
                                    
                                </div>
                                    
                            </div>
                        </div>
                    </a>                   
                <%end%>
            

        </ul>
    </div>
    
    <footer class="">
      <div class="container">
        <img src="https://i.imgur.com/LwK6neL.png" alt="downtitle" class='down_title  img-responsive'>
      </div>
    </footer>
    
    
</div>

app/views/votes/new.html.erb
<div class='container login_form d-flex justify-content-center'>
  <img src="https://i.imgur.com/BVx4rzI.png" alt="Login" class = "img-fluid login_form">
</div>

<div class="container d-flex justify-content-center create_group sign_form">
    <%= form_for(@vote, url: '/demands_new') do |f| %>
        
        
        <%= f.hidden_field :group_id, value: @group_id %>
        <%= f.hidden_field :counter, value: 0 %>
        
        <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true%>
        </div>
        <div class="field">
            <%= f.label :description %><br />
            <%= f.text_field :description, autofocus: true%>
        </div>
        <div class="field">
            <%= f.label :image %><br />
            <%= f.text_field :gravatar_url, autofocus: true%>
        </div>
        <%= f.submit 'create', class: 'btn btn-secondary' %>
    <% end %>
</div>
<div class="group_icon_show d-flex justify-content-center">
    <img src=<%=Group.find_by_id(@group_id).imagen_url%> alt="" class='img-fluid group_new_photo rounded-circle'>
</div>

<div class="foot_icons d-flex justify-content-center mt-5 pt-5">
        
                <div class='d-flex justify-content-center'>
                        <a href=<%= root_url %> class = 'home_button'>
                            <img src="https://i.imgur.com/JcpkRZh.png" alt="" class='img-fluid imagen_vote_show'>
                        </a>
                </div>
                <div class='d-flex justify-content-center '>
                    <a href=<%=  groups_url %> class = 'groups_home_button'>
                        <img src="https://i.imgur.com/xbEKtIa.png" alt="" class='img-fluid imagen_vote_show'>
                    </a>
                </div>
                
                <div class='d-flex justify-content-center '>
                    <a href=<%=  demands_profile_url %> class = 'demands_list_link'>
                        <img src="https://i.imgur.com/MRW2EsQ.png" alt="" class='img-fluid imagen_vote_show'>
                    </a>
                </div>
            </div>

app/views/votes/show.html.erb
<div class="background_votes">
    <div class="name_header">
        <%=@vote.name%>
    </div>

    <div class="container demand">
        <div class="text-center demand_img">
            <img src= <%=@vote.gravatar_url%> alt="demand" class = "img-fluid img-thumbnail demand_img_avatar">
        </div>
        <h1 class= 'demand_description text-justify'>
            <%=@vote.description%>
        </h1>
    
    </div>

    <div class="demand_controls">
        <div class="demand_elements d-flex justify-content-around">
            <a href=<%= demand_update_url(vote:'down', votes_id: @vote.id)  %>>
                <img src= 'https://i.imgur.com/vRbv6wK.png' alt="demand" class = "img-fluid down_arrow">
            </a>
            <span class= 'demand_counter'><%=@vote.counter%></span>
            <a href=<%= demand_update_url(vote:'up', votes_id: @vote.id)  %>>
                <img src= 'https://i.imgur.com/SgIrwNL.png' alt="demand" class = "img-fluid up_arrow">
            </a>
            
        </div>
    </div>

    <div class="foot_icons d-flex justify-content-center mt-5">
        
        <div class='d-flex justify-content-center'>
                <a href=<%= root_url %> class = 'home_button'>
                    <img src="https://i.imgur.com/JcpkRZh.png" alt="" class='img-fluid imagen_vote_show'>
                </a>
        </div>
        <div class='d-flex justify-content-center '>
            <a href=<%=  groups_url %> class = 'groups_home_button'>
                <img src="https://i.imgur.com/xbEKtIa.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
        <div class='d-flex justify-content-center '>
            <a href=<%=  vote_stats_url(votes_id:@vote.id) %> class = 'demand_stats_button'>
                <img src="https://i.imgur.com/XQ0rn90.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
        <div class='d-flex justify-content-center '>
            <a href=<%=  demands_profile_url %> class = 'demands_list_link'>
                <img src="https://i.imgur.com/MRW2EsQ.png" alt="" class='img-fluid imagen_vote_show'>
            </a>
        </div>
    </div>
    
</div>